version: '3'
services:
  web_prod:
    build:
      context: flask
      dockerfile: Dockerfile.prod
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=mongodb://${MONGO_CONNECTION_STRING}
      - FLASK_SECRET_KEY
    volumes:
      - ./user-data/session_data:/usr/src/app/static/session_data
      - ./user-data/upload:/usr/src/app/static/upload
      - ./datasets:/usr/src/app/data
    stop_signal: SIGINT
    # Use existing mongoDB instance on host
volumes:
  web_prod:
