services:
  flask:
    build:
      context: .
      target: prod
    volumes:
      - ./app:/code/app
      - ./misc:/code/misc
      - ./data:/code/data
      - ./pyproject.toml:/code/pyproject.toml
      - ./poetry.lock:/code/poetry.lock
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    networks:
      - lf-net
    environment:
      - APP_ENV
      # for vscode debugger
      - FLASK_APP_DEBUG=true
      # for flask debug mode
      - FLASK_DEBUG=1
      - FLASK_SECRET_KEY
      - MONGO_CONNECTION_STRING
      - DISABLE_CELERY=true
    entrypoint: ["python3", "-m", "app.wsgi"]
