version: '3'
services:
  web:
    build:
      context: flask
      dockerfile: Dockerfile.prod
    environment:
      - DATABASE_URL=mongodb://${MONGO_CONNECTION_STRING}
      - FLASK_SECRET_KEY
    volumes:
      - ./user-data/session_data:/usr/src/app/static/session_data
      - ./user-data/upload:/usr/src/app/static/upload
      - ./datasets:/usr/src/app/data
    stop_signal: SIGINT
    network_mode: "host"
    # Use existing mongoDB instance on host
volumes:
  web:
