services:
  flask:
    build:
      context: ./flask
      target: dev
      args:
        - USER_UID=${USER_UID}
    volumes:
      - ./flask/app:/code/app
      - ./flask/misc:/code/misc
      - ./flask/data:/code/data
      - ./flask/tests:/code/tests
      - ./flask/pyproject.toml:/code/pyproject.toml
      - ./flask/poetry.lock:/code/poetry.lock
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - lf-net
    environment:
      - APP_ENV
      # for vscode debugger
      - FLASK_APP_DEBUG=true
      # for flask debug mode
      - FLASK_DEBUG=1
      - FLASK_SECRET_KEY
      - MONGO_CONNECTION_STRING
      - DISABLE_CELERY=true
      - DISABLE_CACHE=${DISABLE_CACHE:-true}
    entrypoint: ["python3", "-m", "app.wsgi"]
  next:
    image: node:22-slim
    working_dir: /app/locus-focus
    entrypoint: npm run dev
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_SERVER_API_HOST
      - NEXT_PUBLIC_BROWSER_API_HOST
    volumes:
      - "./next:/app"
    ports:
      - "${NEXT_PORT}:3000"
    user: ${USER_UID}
    networks:
      - lf-net
  mongo:
    image:  mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    networks:
      - lf-net

volumes:
  mongo-data:

networks:
  lf-net:
