services:
  flask:
    build:
      context: .
      target: prod
    volumes:
      - ./app:/code/app
      - ./misc:/code/misc
      - ./data:/code/data
      - ./pyproject.toml:/code/pyproject.toml
      - ./poetry.lock:/code/poetry.lock
    ports:
      - 8000:8000
    network_mode: "host"
    environment:
      - APP_ENV=production
      - FLASK_SECRET_KEY
      - MONGO_CONNECTION_STRING
      - DISABLE_CELERY=false
    entrypoint: ["python", "-m", "gunicorn", "--timeout", "6000", "wsgi:app", "--bind=127.0.0.1:8000", "--name", "locusfocus", "--workers=3"]
  celery:
    build:
      context: .
      target: prod
    volumes:
      - ./app:/code/app
      - ./misc:/code/misc
      - ./data:/code/data
      - ./pyproject.toml:/code/pyproject.toml
      - ./poetry.lock:/code/poetry.lock
    network_mode: "host"
    environment:
      - APP_ENV=production
      - FLASK_SECRET_KEY
      - MONGO_CONNECTION_STRING
      - DISABLE_CELERY=false
    entrypoint: ["celery", "-A", "app.tasks", "worker", "--loglevel=info"]
  redis:
    image: redis:7.4.2-alpine
    ports: 
      - 6379:6379
    network_mode: "host"
