services:
  flask:
    build: .
    volumes:
      - ./app:/code/app
      - ./misc:/code/misc
      - ./pyproject.toml:/code/pyproject.toml
      - ./poetry.lock:/code/poetry.lock
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    depends_on:
      - mongo
    networks:
      - lf-net
    environment:
      - APP_ENV
      - FLASK_APP_DEBUG=true
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_DATABASE
    # entrypoint: ["flask","--app", "api.app", "--debug", "run", "--host=0.0.0.0", "--port=${FLASK_PORT}"]
  mongo:
    image:  mongo:6
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    networks:
      - lf-net

volumes:
  mongo-data:

networks:
  lf-net:
