name: Test Flask
on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop

jobs:
  check-flask:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip
      -
        name: Install poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: 1.5.1
      -
        name: Check format and linting
        uses: astral-sh/ruff-action@v3
      -
        name: Unit Test
        env:
            FLASK_SECRET_KEY: abc123
            MONGO_CONNECTION_STRING: mongodb://dummy
        run: |
          poetry install --with dev
          poetry run pytest -W ignore::DeprecationWarning
